"""create_initial_schema

Revision ID: d8301f93155f
Revises: 
Create Date: 2026-03-30 12:57:40.853468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8301f93155f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_caregivers',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsible_caregivers_email'), 'responsible_caregivers', ['email'], unique=True)
    op.create_table('elderly_patients',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('caregiver_id', sa.UUID(), nullable=False),
    sa.Column('chronic_conditions', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['responsible_caregivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elderly_patients_caregiver_id'), 'elderly_patients', ['caregiver_id'], unique=False)
    op.create_table('medications',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('dose_mg', sa.Float(), nullable=False),
    sa.Column('frequency_hours', sa.Integer(), nullable=False),
    sa.Column('with_food', sa.Boolean(), nullable=False),
    sa.Column('current_stock_units', sa.Integer(), nullable=False),
    sa.Column('minimum_stock_units', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['elderly_patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('medication_alerts',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['elderly_patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_alerts_medication_id'), 'medication_alerts', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_alerts_patient_id'), 'medication_alerts', ['patient_id'], unique=False)
    op.create_table('scheduled_doses',
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_doses_medication_id'), 'scheduled_doses', ['medication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_doses_medication_id'), table_name='scheduled_doses')
    op.drop_table('scheduled_doses')
    op.drop_index(op.f('ix_medication_alerts_patient_id'), table_name='medication_alerts')
    op.drop_index(op.f('ix_medication_alerts_medication_id'), table_name='medication_alerts')
    op.drop_table('medication_alerts')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_elderly_patients_caregiver_id'), table_name='elderly_patients')
    op.drop_table('elderly_patients')
    op.drop_index(op.f('ix_responsible_caregivers_email'), table_name='responsible_caregivers')
    op.drop_table('responsible_caregivers')
    # ### end Alembic commands ###
